platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# pod 'leveldb-library', :path => './leveldb-library-src'
# pod 'GoogleUtilities'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
      
      if target.name == 'GoogleUtilities'
        # Force all headers to be public
        target.headers_build_phase.files.each do |file|
          file.settings = { 'ATTRIBUTES' => ['Public'] }
        end
        
        # Add header search paths for nested structure
        config.build_settings['HEADER_SEARCH_PATHS'] ||= []
        config.build_settings['HEADER_SEARCH_PATHS'] << '$(SRCROOT)/Pods/GoogleUtilities'
        config.build_settings['HEADER_SEARCH_PATHS'] << '$(SRCROOT)/Pods/GoogleUtilities/GoogleUtilities'
        config.build_settings['HEADER_SEARCH_PATHS'] << '$(SRCROOT)/Pods/GoogleUtilities/third_party/IsAppEncrypted'
      end
      
      # Add FlutterMacOS framework search path
      if config.build_settings['FRAMEWORK_SEARCH_PATHS']
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/../Flutter/ephemeral'
      else
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = ['${PODS_ROOT}/../Flutter/ephemeral']
      end
      
      # Add header search paths for FlutterMacOS
      if config.build_settings['HEADER_SEARCH_PATHS']
        config.build_settings['HEADER_SEARCH_PATHS'] << '${PODS_ROOT}/../Flutter/ephemeral/FlutterMacOS.framework/Headers'
      else
        config.build_settings['HEADER_SEARCH_PATHS'] = ['${PODS_ROOT}/../Flutter/ephemeral/FlutterMacOS.framework/Headers']
      end
    end
  end
end